queue_rules:
  - name: default
    queue_conditions:
      - base=main
    merge_conditions:
      - check-success=test_authz_bypass
    merge_method: merge
    checks_timeout: 300

pull_request_rules:
  - name: Queue PR on default
    conditions:
      - base=main
    actions:
      queue:
        name: default
